
<header id="header">
		<div class="headerItems">
			<!-- Logotipo -->
			<a href="index.php">
				<div><img src="recursos/pretilg.png" alt="Preti Logo" class="imagen"></div>
				<div class="display-medium display-great"><h1>Preti.</h1></div>
				<div class="display-great"><h2>Creativity & Beyond</h2></div>
			</a>
		</div>

		<input type="checkbox" id="ckburger">
		<nav id="navbar">
		</nav>
</header>